### ISSUE TITLE
When files are included from sub-directory the destination file winds up in the wrong place

### ISSUE THREAD

**Issue by spfiedler** [unlight/gulp-cssimport#12]
Here is my directory structure:

drive/company/project/home/
drive/company/project/home/src/
drive/company/project/home/src/patterns/
drive/company/project/home/src/patterns/patterns.less

drive/company/project/home/src/patterns/directives/
drive/company/project/home/src/patterns/directives/containers/
drive/company/project/home/src/patterns/directives/containers/groupBox/
drive/company/project/home/src/patterns/directives/containers/groupBox/group-box.less
drive/company/project/home/src/patterns/directives/elements/
drive/company/project/home/src/patterns/directives/elements/footer/
drive/company/project/home/src/patterns/directives/elements/footer/footer.less
drive/company/project/home/src/patterns/directives/feedback/
drive/company/project/home/src/patterns/directives/feedback/alertBox/
drive/company/project/home/src/patterns/directives/elements/footer/alertBox.less

The file that drives this is the 'patterns.less' file which contains imports:
----------
// injector
@import 'directives/containers/groupBox/group-box.less';
@import 'directives/elements/footer/footer.less';
@import 'directives/feedback/alertBox/alert-box.less';
// endinjector

/** Global UX Patterns **/

h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4, .h5, .h6 {
  font-family: 'Montserrat';
}
--------

Now my drive/company/project/gulpfile.js has a task to create a SINGLE less file by including the imports:
--------
gulp.task('styles:less', function() {
  gulp.src('src/uxpatterns/patterns.less')
    .pipe(cssimport())
    .pipe(gulp.dest('dist/'));
});
--------

I expect a file containing all the imported files to be at drive/company/project/home/dist/patterns.less.

HOWEVER, the file appears in the drive/ directory.  

The content is correct, it's just that the DESTINATION IS WRONG.  

As a workaround I have to code my gulpfile to declare a phoney destination:
---------
gulp.task('styles:less', function() {
  gulp.src('src/patterns/patterns.less')
    .pipe(cssimport())
    // this is a hack due to a defect in cssimport
    // - we shouldn't have to add a/b/c/
    // - the directory is updated in the 'contents' object and shouldn't be
    .pipe(gulp.dest('dist/a/b/c/'));
});
---------

**Comment by unlight** [comment]
Have you tried
`gulp.src('src/uxpatterns/patterns.less', { base: 'src/uxpatterns' })`
?

Thanks for bug report, probably dup https://github.com/unlight/gulp-cssimport/issues/10
Can you try version 1.X? (`npm i gulp-cssimport@1`)
But has some restricts (see changelog)

**Comment by spfiedler** [comment]
I just tried that, but unfortunately, it does not work.  Good try, though.


Steve Fiedler  |  Principal UI Software Engineer
O 339.674.2548  |  M 508.561.5308
[veracode-email-logo]

The Most Powerful Application Security Platform on the Planet

**Comment by mdfragala** [comment]
I noticed something odd debugging the source of this issue initially. In my situation, I had two files being processed &mdash; `./src/css/index.css/` ending up `./app/assets/index.css` and `./src/css/vendors/glide.css` as `./app/assets/css/vendors/glide.css`. The `index.css` file was getting dumped on directory too soon.

But logging it's file path at various points in the task never reported any change. I thought maybe `gulp-cssimport` was messing with the path, but it remained `./src/css/index.css` all the way until it hit `gulp.dest`. I know it's still an issue of this plugin since removing it fixes the turnout.

Not sure if this helps, but I hope it does!

**Comment by unlight** [comment]
I have rewritten part with resolving paths, which leads to bogus destination paths.
Please, try new vesrsion `npm i unlight/gulp-cssimport#3.0`, it is not published yet @ npm.

**Comment by unlight** [comment]
FIxed in 3.0+
