### ISSUE TITLE
Corrupted Package in 2.1.0 on npm?

### ISSUE THREAD

**Issue by OClement** [unlight/gulp-cssimport#14]
I could not install the latest version through npm

>Installing 2.0.0 worked fine

Here's the error I get when installing the latest:

```
$ npm install gulp-cssimport
npm ERR! Darwin 14.5.0
npm ERR! argv "~/.nvm/versions/node/v5.1.0/bin/node" "~/.nvm/versions/node/v5.1.0/bin/npm" "install" "gulp-cssimport"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code EREADFILE

npm ERR! Error extracting ~/.npm/gulp-cssimport/2.1.0/package.tgz archive: ENOENT: no such file or directory, open '~/.npm/gulp-cssimport/2.1.0/package.tgz'
npm ERR! 
```

**Comment by unlight** [comment]
@OClement 
Are you still having errors while install?

**Comment by OClement** [comment]
Yup, just tried it now
`npm ERR! Error extracting /Users/oclement/.npm/gulp-cssimport/2.1.0/package.tgz archive: ENOENT: no such file or directory, open '/Users/oclement/.npm/gulp-cssimport/2.1.0/package.tgz'`

For the record, I just thought about the fact that I am using Node v5.1 and Npm 3.3.2

I just tried with node 0.12.8 and it works fine
So there must be something breaking in between the node versions

**Comment by unlight** [comment]
I tried `npm i gulp-cssimport` on *node 5.1.0/npm 3.5.0* and it works fine.
And it installs version `2.1.1-b` this is the latest version, not `2.1.0`.  
`npm i gulp-cssimport@2.1.0` - also works fine for me.

[package.json@2.1.0](https://raw.githubusercontent.com/unlight/gulp-cssimport/c307b312298a515f2fa057146787829105a7128b/package.json)
Json is valid.

Text in first comment contains `npm ERR! argv "~/.nvm/versions/node/v5.1.0/bin/node"`
Maybe it some kind problem with nvm?

**Comment by OClement** [comment]
Either that or I still have a cached package and it tried to reinstall this instead of the latest one maybe?

I'll see if I can clean the cache and try again

O.

**Comment by unlight** [comment]
Also you can try to install directly from github.
`npm i unlight/gulp-cssimport`
or
`npm i https://github.com/unlight/gulp-cssimport/archive/tar.gz`

**Comment by pkornev** [comment]
I've got same issue.

**Comment by OClement** [comment]
@unlight Sorry for the delay

Cleaning cache didn't help
Still failing under Node 5.1.x -> Using NVM (OS X)

I'm not in a position to remove NVM from the equation on my machine at this moment

@pkornev Whats your current setup? Node/NPM versions, using nvm or not? Windows or Linux or OS X?
These infos would help

**Comment by pavelkornev** [comment]
@OClement

$ npm -v
3.3.9

$ node -v
v5.0.0

OSX.

**Comment by djhworld** [comment]
Same issue here, OSX 

* node v5.2.0
* npm  v3.3.12

**Comment by unlight** [comment]
Hmm, looks like something wrong with npm versioning. I've reproduced this bug on my work machine. Bumping version to `2.1.1-b` to `2.1.2` fixed the issue.
@OClement @pavelkornev @djhworld 
Could you try again, and tell the result?
