### ISSUE TITLE
File masks like **/* cause wrong path resolving

### ISSUE THREAD

**Issue by ln-e** [unlight/gulp-cssimport#15]
When i define glob something like `gulp.src("../src/**/style.css")` plugin try to find imported urls in src directory, not in sub directory, where file really is.

node v5.0.0
css-import 2.1.2

**Comment by unlight** [comment]
I have rewritten part with resolving paths, which leads to bogus destination paths.
Please, try new version `npm i unlight/gulp-cssimport#3.0`, it is not published yet @ npm.

**Comment by unlight** [comment]
FIxed in 3.0+
