### ISSUE TITLE
Plugin remove sourcemaps from end file.

### ISSUE THREAD

**Issue by delch** [unlight/gulp-cssimport#16]
gulpfile.babel.js

```javascript
import cssimport from 'gulp-cssimport';

gulp.task('sass', function(){
  return gulp
    .src(PATH.SASS.MAIN)
    .pipe(sourcemaps.init())
    .pipe(sass())
    .pipe(cssimport())
    .pipe(sourcemaps.write())
    .pipe(gulp.dest(PATH.BUILD.CSS))
    .pipe(connect.reload());
});
```
No sourcemaps inside file, but if i remove cssimport(), sourcemaps work fine.

**Comment by unlight** [comment]
Unfortunately, plugin does not support gulp-sourcemaps.
You can find [here a list of supported plugins](https://github.com/floridoo/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support)

**Comment by unlight** [comment]
I will try to add. Stay tuned.

**Comment by unlight** [comment]
Fixed in 3.0+. It is not published yet @ npm.
Please, try new version `npm i unlight/gulp-cssimport#3.0`.

**Comment by SuperOl3g** [comment]
I've try this variant `npm i unlight/gulp-cssimport#3.0.`
But still don't work. Maybe becouse I use it with Sass?
You can check by yourself
https://github.com/SuperOl3g/start_box

**Comment by unlight** [comment]
> // ломает сорсмапы :<

:laughing:

**Comment by SuperOl3g** [comment]
I relied on another kind of reaction to this problem)

**Comment by SuperOl3g** [comment]
Привет, я смотрю с созданием сорсмапов дела не продвинулись.
Мб я смогу тебе помочь в их написании, а то уж очень нравится твой плагин, удобный синтаксис.

**Comment by unlight** [comment]
Пул-реквесты принимаются, спасибо.
