### ISSUE TITLE
Commented @import statements are not ignored

### ISSUE THREAD

**Issue by ragol** [unlight/gulp-cssimport#19]
Commented `@import` statement do not get skipped. It does not matter whether `@import` is located inside a block comment `/* */` or in an inline comment `//`. The corresponding regular expression in https://github.com/unlight/gulp-cssimport/blob/master/gulp-cssimport.js#L50 does not check for comments.

For example:
```
// foo.scss:
// @import "bar.scss";
/*
@import "bar.scss";
*/

// bar.scss:
$x: 5px;
```

The issue can be solved by stripping comments before executing the parsing regular expression.

**Comment by Schweinepriester** [comment]
+1
