### ISSUE TITLE
Can it work with absolute path ?

### ISSUE THREAD

**Issue by yikuo123** [unlight/gulp-cssimport#22]
for example:
@import url("/_test/css/c.css");

**Comment by unlight** [comment]
Is it bug report or question?

**Comment by yikuo123** [comment]
I  tried using it with absolute path, but it didn't work. Maybe there was something wrong with my way.

**Comment by unlight** [comment]
> I tried using it with absolute path, but it didn't work. 

I've checked. It shoud work. If you do not see error or expected result, probably, you are doing something wrong.

**Comment by yikuo123** [comment]
![image](https://cloud.githubusercontent.com/assets/13978174/24574035/81f09764-16bf-11e7-9cfc-0265dd71e5b7.png)
![qq 20170401095533](https://cloud.githubusercontent.com/assets/13978174/24576222/867b8ebc-16ea-11e7-8a5d-6c40ec8ea53d.png)
![qq 20170401095451](https://cloud.githubusercontent.com/assets/13978174/24576223/867c43ca-16ea-11e7-9bf8-73ed6c32c7e8.png)


As shown in these pictures, I imported c.css in base.css with absolute path, and it didn't work . 
Could you tell me how to make it work ?  Thanks very much.

**Comment by unlight** [comment]
You assumed that it is absolute url, but it is not (it's root relative path).
To make it work you need specify:
1. absolute url (with protocol and domain) e.g. `http://example.com/a/b.css`
2. absolute path or relative filesystem path 

css file usually doesnt know where its hosted.
