### ISSUE TITLE
when i use cssimport throw UnhandledPromiseRejectionWarning and DeprecationWarning

### ISSUE THREAD

**Issue by hlshang** [unlight/gulp-cssimport#23]
node:953) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: write callback called multiple times
(node:953) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

some css file success but some not

**Comment by unlight** [comment]
Looks like same issue #24
