### ISSUE TITLE
css @import inside imported file

### ISSUE THREAD

**Issue by divdoctor** [unlight/gulp-cssimport#24]
Hello. Thank you for the great plugin, but I have some troubles. I saw this error after I had finished my project:
`(node:3312) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error in plugin 'gulp-cssimport'
Message:
    socket hang up
Details:
    code: ECONNRESET
(node:3312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Everything had compiled well before I interrupted gulp. Sometimes, maybe, in one case of ten there are no errors and gulp runs properly. I had this import:
`@import '../../node_modules/admin-lte/dist/css/AdminLTE.css';`

I found that this line in imported css causes the problem:
`@import url(https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic);`
If I delete this, the problem disappears.

**Comment by unlight** [comment]
> Sometimes, maybe, in one case of ten

Plugin tries to download remote file. And sometimes it can fail because of:
Remote server is down or Your connection is broken, other network issues.

To easy detect node warning such as `Unhandled promise rejections are deprecated`, use
https://github.com/sindresorhus/loud-rejection
