### ISSUE TITLE
 Add 'root' option and 'urlTransform' option

### ISSUE THREAD

**Issue by gauntface** [unlight/gulp-cssimport#25]
CSS imports can be absolute paths on a web server where '/styles/...' could be a valid server path, but relate to a different path on the file systme (i.e. '/public/styles/...'). Would you be open to adding the following options to solve this use case:

- `root`: A path that is pre-pended to absolute paths used
- `urlTransform`: a function that is called with each discovered importPath and can return an alternative import path (allows developers to use a development version of a file while working on the source but switch to an optimsed version later on).

**Comment by unlight** [comment]
@gauntface
Seems that `urlTransform` more general approach and overlaps `root` feature.
Why do we need both?

**Comment by gauntface** [comment]
Agreed, root would just cover the most common use case and urlTransform is the more involved option

**Comment by unlight** [comment]
Implemented [transform](https://github.com/unlight/gulp-cssimport#transform) option
