### ISSUE TITLE
Imported CSS files contain byte order mark

### ISSUE THREAD

**Issue by allesmi** [unlight/gulp-cssimport#26]
While investigating why some elements in my markup where not styled as intended I found out that the merged CSS files still contain the UTF-8 byte order mark (BOM).

The original separate files are saved as UTF-8 with BOM and these BOMs end up in the merged CSS file. Other (gulp) plugins such as strip-bom are of no help, as these operate only on the first byte in a file.

Open for discussion is wether handling the case within gulp-cssimport or changing the input file encoding is more appropriate.

**Comment by unlight** [comment]
Cannot imaginate how BOM can corrupt design.
But imo bom should be removed in result css.

**Comment by allesmi** [comment]
Hey, thank you for your reply. I set up a small example project where this problem occurs. https://github.com/allesmi/cssimport-bom

**Comment by unlight** [comment]
Thanks for example repository.
I've just published version 6.0.0 with the fix
https://www.npmjs.com/package/gulp-cssimport
