### ISSUE TITLE
recursive inclusion?

### ISSUE THREAD

**Issue by bmacnaughton** [unlight/gulp-cssimport#6]
It would be great if this would descend into each file it imports and perform imports included in those files.

**Comment by DaanDD** [comment]
+1

**Comment by alp82** [comment]
+1

**Comment by paulmist** [comment]
+1

**Comment by unlight** [comment]
The work is started. New version will be released soon.

**Comment by unlight** [comment]
Implemented in v2.0.0.

**Comment by paulmist** [comment]
Thank you.
