### ISSUE TITLE
is it rebase images url ?

### ISSUE THREAD

**Issue by Samlv9** [unlight/gulp-cssimport#9]
```css
@import url(widgets/a.css);

```

in the `a.css` i have :
``` css
.a {
     background: url(../../images/a.png);
}

how can i get correct url when combine all @imports ?

**Comment by unlight** [comment]
Hello.
The answer is no, content of the file inserts as is.

**Comment by unlight** [comment]
@Samlv9 
Have you tried this https://github.com/kjbekkelund/gulp-css-rebase-urls ?

**Comment by unlight** [comment]
Closing anyway, rebase is related to this plugin.
